// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package dialog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Oudwins/tailwind-merge-go/pkg/twmerge"
	"github.com/rotemhoresh/shadcn-templ/primitives/dialog"
)

const titleClass = "text-lg font-semibold leading-none tracking-tight"

type TitleProps = dialog.TitleProps

func Title(props TitleProps) templ.Component {
	props.Class = twmerge.Merge(titleClass, props.Class)
	return dialog.Title(props)
}

var _ = templruntime.GeneratedTemplate
