// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package dialog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

// There is no element for dialog close, just add these attributes to your component.
var Close = templ.Attributes{
	"x-on:click": fmt.Sprintf("%s = false", control),
}

var _ = templruntime.GeneratedTemplate
