// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package dialog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	p "github.com/rotemhoresh/shadcn-templ/primitives"
)

// There is no element for dialog trigger, just add these attributes to your component.
var Trigger = templ.Attributes{
	"aria-haspopup":  "dialog",
	":aria-expanded": control,
	":aria-controls": p.Id(scopeName, contentName),
	":data-state":    getState(control),
	"x-on:click":     fmt.Sprintf("%s = true", control),
}

var _ = templruntime.GeneratedTemplate
