// Code generated by "optaliase_generator.go -type=RootProps"; DO NOT EDIT.

package progress

import "github.com/rotemhoresh/shadcn-templ/ui"

var (
	WithClass = ui.WithClass[*RootProps]
	WithAttrs = ui.WithAttrs[*RootProps]
	WithAttr  = ui.WithAttr[*RootProps]
)
